repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
