version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - ${MONGODB_HOST:-127.0.0.1:27017}:27017
    volumes:
    - mongo:/data/db
    - mongo:/data/configdb
  redis:
    image: redis:alpine
    ports:
      - ${REDIS_HOST:-127.0.0.1:6379}:6379
    volumes:
    - redis:/data

  rabbitmq:
    image: itzg/rabbitmq-stomp:latest
    ports:
      - ${RABBIT_HOST:-127.0.0.1:61613}:61613

volumes:
  redis:
  mongo:
