version: "3.8"

services:
  flask:
    build: .
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo
    ports:
      - ${FLASK_RUN_HOST-127.0.0.1}:${FLASK_RUN_PORT:-5000}:5000
    entrypoint: flask run
    volumes:
      - .:/app
  jupyter:
    build: .
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo
    ports:
      - ${JUPYTER_RUN_HOST-127.0.0.1}:${JUPYTER_RUN_PORT:-8888}:8888
    entrypoint: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root
    volumes:
    - .:/app
  worker:
    build: .
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo
      - redis
    entrypoint: celery -A worker:app worker --loglevel=${CELERY_LOG_LEVEL:-INFO}
    volumes:
      - .:/app
