version: "3.8"

services:
  flask:
    build: .
    depends_on:
      - mongo
    ports:
      - ${FLASK_RUN_HOST-127.0.0.1}:${FLASK_RUN_PORT:-5000}:80
  worker:
    build: .
    depends_on:
      - mongo
      - redis
    entrypoint: celery -A worker:app worker --loglevel=${CELERY_LOG_LEVEL:-ERROR}
