"""This module contains key names for pipeline configs"""

DEVICE = "device"
WRITER = "writer"
VERBOSE = "verbose"
LABELS = "labels"
METRICS = "metrics"
LOSS = "loss"
ACCURACY = "accuracy"
CLASSIFICATION_REPORT = "classification_report"
