# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FLASK_ENV: testing

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync --dev

    - name: Test with pytest
      run: |
        pipenv run pytest -n 4

    - name: Lint with pylint
      run: |
        pipenv run pylint recommender tasks

    - name: Check with black
      run: |
        pipenv run black --check recommender tasks


